export const openApiDocument = {
  openapi: "3.0.3",
  info: {
    title: "BookWise AI API",
    version: "0.1.0",
    description:
      "HTTP API for BookWise AI. This initial document covers the server health endpoint; future API documentation will be generated by tsoa.",
  },
  servers: [
    {
      url: "/api",
      description: "Current server",
    },
  ],
  tags: [
    {
      name: "Health",
      description: "Server availability and status",
    },
  ],
  paths: {
    "/health": {
      get: {
        operationId: "getHealth",
        summary: "Get server health",
        description: "Confirms that the BookWise API process is accepting requests.",
        tags: ["Health"],
        responses: {
          "200": {
            description: "The server is healthy.",
            content: {
              "application/json": {
                schema: {
                  $ref: "#/components/schemas/HealthResponse",
                },
              },
            },
          },
          "500": {
            description: "An unexpected server error occurred.",
            content: {
              "application/json": {
                schema: {
                  $ref: "#/components/schemas/ErrorResponse",
                },
              },
            },
          },
        },
      },
    },
  },
  components: {
    schemas: {
      HealthResponse: {
        type: "object",
        required: ["status", "service", "timestamp"],
        properties: {
          status: {
            type: "string",
            enum: ["ok"],
            example: "ok",
          },
          service: {
            type: "string",
            example: "bookwise-server",
          },
          timestamp: {
            type: "string",
            format: "date-time",
            example: "2026-08-13T15:39:57.870Z",
          },
        },
      },
      ErrorResponse: {
        type: "object",
        required: ["error"],
        properties: {
          error: {
            type: "object",
            required: ["code", "message", "requestId"],
            properties: {
              code: {
                type: "string",
                example: "INTERNAL_SERVER_ERROR",
              },
              message: {
                type: "string",
                example: "An unexpected error occurred",
              },
              requestId: {
                type: "string",
                format: "uuid",
              },
            },
          },
        },
      },
    },
  },
} as const;
